name: Secondary Workflow
on:
    workflow_call:
        inputs:
            messages:
                required: true
                type: string
jobs:
    display-message:
        runs-on: ubuntu-latest
        steps:
            - name: Display the message
              run: echo "${{ inputs.messages }}"
